import type { Metadata } from "next";
import { Provider } from "jotai";
import NonSSR from "@/components/NonSSR";
import { Barlow } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";

const barlow = Barlow({ weight: "500", subsets: ["latin", "latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
          />
        </head>
        <body
          className={cn(
            barlow.className,
            `antialiased bg-[#f5f5f5] md:max-h-[100dvh] md:max-w-[100dvw] 
            p-[env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)]`
          )}
        >
          <div className="flex flex-col py-16 overflow-hidden max-h-[100dvh]">
            <Header />
            <div className="flex-1  overflow-y-auto overflow-x-hidden p-2">
              <main className="mx-auto w-full">{children}</main>
              <NonSSR showInfo={false} />
            </div>
            <NavBar />
          </div>
        </body>
      </html>
    </Provider>
  );
}
